dataset: "CIFAR"
loader: "CIFAR"
directory: "CIFAR"
N: 20000
K: 500

bayes_model: "Resnet"
training:
  epochs: 70
  learning_rate: 0.001
  batch_size: 128

models:
  - ./configs/cifar_Linear.yaml
  - ./configs/cifar_Resnet.yaml

